### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by shaungehring** [guedes/exjson#34] opened 2016-02-10 21:52 UTC
warning: the dependency :exjson requires Elixir "0.13.0" but you are running on v1.1.1
Compiled lib/exjson.ex
Compiled lib/exjson/deprecation.ex

== Compilation error on file lib/exjson/parser.ex ==
** (CompileError) lib/exjson/parser.ex:18: function atom_to_binary/1 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

**Comment by guedes** [comment] 2016-02-10 23:18
Hi! Thank you for reporting this error. I'd like to know from where it came from? I saw this message `warning: the dependency` and wondering if the dependency config are "forcing" an old `exjson`  version.

**Comment by guedes** [comment] 2016-02-23 00:27
Since I can't reproduce this I'm closing this by now. Let me know whether this still failing.

Happy coding! :)

**Closed by guedes** 2016-02-23 00:27 UTC
