### ISSUE TITLE
Won't seem to parse non-string keys

### ISSUE THREAD

**Issue by jbailey** [guedes/exjson#14] opened 2013-10-11 20:23 UTC
Reason: (Protocol.UndefinedError) protocol Access not implemented for {1, :json_parser, ['syntax error before: ', 'email']}

```json
{ email: "test@example.com", name: "John Smith" }
```

**Comment by guedes** [comment] 2016-02-23 00:27
Since I can't reproduce this I'm closing this by now. Let me know whether this still failing.

Happy coding!

**Closed by guedes** 2016-02-23 00:27 UTC
